on: [pull_request]

jobs:
  cdk_build_job:
    runs-on: ubuntu-latest
    name: Build CDK stacks
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CDK Synthesize
        uses: .github/actions
        with:
          cdk_command: synthesize
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'

      - name: CDK Diff
        uses: .github/actions
        with:
          cdk_command: diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'