on:
  push:
    branches:
    - main

jobs:
  cdk_deploy_job:
    runs-on: ubuntu-latest
    name: Deploy CDK stacks
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CDK Synthesize
        uses: ./
        with:
          cdk_command: synthesize
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'

      - name: CDK Diff
        uses: ./
        with:
          cdk_command: diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'

      - name: CDK Deploy
        uses: ./
        with:
          cdk_command: deploy
          cdk_stack: --all
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'